/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

public class App {
    public static void main(String[] args) {
        // TODO: Get filePath
        // TODO: Define QuoteReader with file path
        // TODO: Get random Quote object by calling some method of QuoteReader

        // TODO: Sout the info
    }
}
